export interface OverseasItem {
  symbol: string;
  name: string;
  exchange: 'NASDAQ' | 'NYSE';
}

export const OVERSEAS_LIST: OverseasItem[] = [
  // ── NASDAQ ────────────────────────────────────
  { symbol: 'AAPL',  name: 'Apple',              exchange: 'NASDAQ' },
  { symbol: 'MSFT',  name: 'Microsoft',           exchange: 'NASDAQ' },
  { symbol: 'NVDA',  name: 'NVIDIA',              exchange: 'NASDAQ' },
  { symbol: 'AMZN',  name: 'Amazon',              exchange: 'NASDAQ' },
  { symbol: 'GOOGL', name: 'Alphabet (GOOGL)',     exchange: 'NASDAQ' },
  { symbol: 'GOOG',  name: 'Alphabet (GOOG)',      exchange: 'NASDAQ' },
  { symbol: 'META',  name: 'Meta Platforms',       exchange: 'NASDAQ' },
  { symbol: 'TSLA',  name: 'Tesla',               exchange: 'NASDAQ' },
  { symbol: 'AVGO',  name: 'Broadcom',            exchange: 'NASDAQ' },
  { symbol: 'COST',  name: 'Costco',              exchange: 'NASDAQ' },
  { symbol: 'NFLX',  name: 'Netflix',             exchange: 'NASDAQ' },
  { symbol: 'AMD',   name: 'AMD',                 exchange: 'NASDAQ' },
  { symbol: 'INTC',  name: 'Intel',               exchange: 'NASDAQ' },
  { symbol: 'QCOM',  name: 'Qualcomm',            exchange: 'NASDAQ' },
  { symbol: 'AMAT',  name: 'Applied Materials',   exchange: 'NASDAQ' },
  { symbol: 'LRCX',  name: 'Lam Research',        exchange: 'NASDAQ' },
  { symbol: 'MU',    name: 'Micron Technology',   exchange: 'NASDAQ' },
  { symbol: 'ASML',  name: 'ASML Holding',        exchange: 'NASDAQ' },
  { symbol: 'TXN',   name: 'Texas Instruments',   exchange: 'NASDAQ' },
  { symbol: 'KLAC',  name: 'KLA Corp',            exchange: 'NASDAQ' },
  { symbol: 'ADI',   name: 'Analog Devices',      exchange: 'NASDAQ' },
  { symbol: 'MRVL',  name: 'Marvell Technology',  exchange: 'NASDAQ' },
  { symbol: 'PANW',  name: 'Palo Alto Networks',  exchange: 'NASDAQ' },
  { symbol: 'CRWD',  name: 'CrowdStrike',         exchange: 'NASDAQ' },
  { symbol: 'SNPS',  name: 'Synopsys',            exchange: 'NASDAQ' },
  { symbol: 'CDNS',  name: 'Cadence Design',      exchange: 'NASDAQ' },
  { symbol: 'ADBE',  name: 'Adobe',               exchange: 'NASDAQ' },
  { symbol: 'CRM',   name: 'Salesforce',          exchange: 'NYSE'   },
  { symbol: 'NOW',   name: 'ServiceNow',          exchange: 'NYSE'   },
  { symbol: 'ORCL',  name: 'Oracle',              exchange: 'NYSE'   },
  { symbol: 'CSCO',  name: 'Cisco',               exchange: 'NASDAQ' },
  { symbol: 'INTU',  name: 'Intuit',              exchange: 'NASDAQ' },
  { symbol: 'ISRG',  name: 'Intuitive Surgical',  exchange: 'NASDAQ' },
  { symbol: 'REGN',  name: 'Regeneron',           exchange: 'NASDAQ' },
  { symbol: 'GILD',  name: 'Gilead Sciences',     exchange: 'NASDAQ' },
  { symbol: 'AMGN',  name: 'Amgen',               exchange: 'NASDAQ' },
  { symbol: 'ADP',   name: 'ADP',                 exchange: 'NASDAQ' },
  { symbol: 'SBUX',  name: 'Starbucks',           exchange: 'NASDAQ' },
  { symbol: 'PYPL',  name: 'PayPal',              exchange: 'NASDAQ' },
  { symbol: 'ABNB',  name: 'Airbnb',              exchange: 'NASDAQ' },
  { symbol: 'UBER',  name: 'Uber',                exchange: 'NYSE'   },
  { symbol: 'LYFT',  name: 'Lyft',                exchange: 'NASDAQ' },
  { symbol: 'SNAP',  name: 'Snap',                exchange: 'NYSE'   },
  { symbol: 'SPOT',  name: 'Spotify',             exchange: 'NYSE'   },
  // ── NYSE ─────────────────────────────────────
  { symbol: 'BRK-B', name: 'Berkshire Hathaway',  exchange: 'NYSE'   },
  { symbol: 'JPM',   name: 'JPMorgan Chase',       exchange: 'NYSE'   },
  { symbol: 'V',     name: 'Visa',                 exchange: 'NYSE'   },
  { symbol: 'MA',    name: 'Mastercard',           exchange: 'NYSE'   },
  { symbol: 'UNH',   name: 'UnitedHealth',         exchange: 'NYSE'   },
  { symbol: 'XOM',   name: 'Exxon Mobil',          exchange: 'NYSE'   },
  { symbol: 'CVX',   name: 'Chevron',              exchange: 'NYSE'   },
  { symbol: 'PG',    name: 'P&G',                  exchange: 'NYSE'   },
  { symbol: 'JNJ',   name: 'Johnson & Johnson',    exchange: 'NYSE'   },
  { symbol: 'WMT',   name: 'Walmart',              exchange: 'NYSE'   },
  { symbol: 'HD',    name: 'Home Depot',           exchange: 'NYSE'   },
  { symbol: 'BAC',   name: 'Bank of America',      exchange: 'NYSE'   },
  { symbol: 'WFC',   name: 'Wells Fargo',          exchange: 'NYSE'   },
  { symbol: 'GS',    name: 'Goldman Sachs',        exchange: 'NYSE'   },
  { symbol: 'MS',    name: 'Morgan Stanley',       exchange: 'NYSE'   },
  { symbol: 'BLK',   name: 'BlackRock',            exchange: 'NYSE'   },
  { symbol: 'SCHW',  name: 'Charles Schwab',       exchange: 'NYSE'   },
  { symbol: 'LLY',   name: 'Eli Lilly',            exchange: 'NYSE'   },
  { symbol: 'PFE',   name: 'Pfizer',               exchange: 'NYSE'   },
  { symbol: 'MRK',   name: 'Merck',                exchange: 'NYSE'   },
  { symbol: 'ABBV',  name: 'AbbVie',               exchange: 'NYSE'   },
  { symbol: 'TMO',   name: 'Thermo Fisher',        exchange: 'NYSE'   },
  { symbol: 'DHR',   name: 'Danaher',              exchange: 'NYSE'   },
  { symbol: 'DIS',   name: 'Disney',               exchange: 'NYSE'   },
  { symbol: 'CMCSA', name: 'Comcast',              exchange: 'NASDAQ' },
  { symbol: 'NWSA',  name: 'News Corp',            exchange: 'NASDAQ' },
  { symbol: 'CAT',   name: 'Caterpillar',          exchange: 'NYSE'   },
  { symbol: 'DE',    name: 'John Deere',           exchange: 'NYSE'   },
  { symbol: 'BA',    name: 'Boeing',               exchange: 'NYSE'   },
  { symbol: 'GE',    name: 'GE Aerospace',         exchange: 'NYSE'   },
  { symbol: 'RTX',   name: 'RTX Corp',             exchange: 'NYSE'   },
  { symbol: 'LMT',   name: 'Lockheed Martin',      exchange: 'NYSE'   },
  { symbol: 'NOC',   name: 'Northrop Grumman',     exchange: 'NYSE'   },
  { symbol: 'TSM',   name: 'TSMC',                 exchange: 'NYSE'   },
  { symbol: 'SONY',  name: 'Sony',                 exchange: 'NYSE'   },
  { symbol: 'TM',    name: 'Toyota',               exchange: 'NYSE'   },
  { symbol: 'HMC',   name: 'Honda',                exchange: 'NYSE'   },
  { symbol: 'NVO',   name: 'Novo Nordisk',         exchange: 'NYSE'   },
  { symbol: 'SHOP',  name: 'Shopify',              exchange: 'NYSE'   },
  { symbol: 'COIN',  name: 'Coinbase',             exchange: 'NASDAQ' },
  { symbol: 'MSTR',  name: 'MicroStrategy',        exchange: 'NASDAQ' },
  { symbol: 'ARM',   name: 'Arm Holdings',         exchange: 'NASDAQ' },
  { symbol: 'SMCI',  name: 'Super Micro Computer', exchange: 'NASDAQ' },
  { symbol: 'PLTR',  name: 'Palantir',             exchange: 'NASDAQ' },
  { symbol: 'AI',    name: 'C3.ai',                exchange: 'NYSE'   },
  { symbol: 'SOUN',  name: 'SoundHound AI',        exchange: 'NASDAQ' },
  { symbol: 'IONQ',  name: 'IonQ',                 exchange: 'NYSE'   },
];

export function searchOverseasList(query: string, limit = 10): OverseasItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return OVERSEAS_LIST.filter(
    (s) => s.symbol.toLowerCase().includes(q) || s.name.toLowerCase().includes(q)
  ).slice(0, limit);
}
